### ISSUE TITLE
Examples or description of the behavior

### ISSUE THREAD

**Issue by oyeanuj** [pmkary/Righteous#3]
Hi @pmkary, I came here via your themes. I was curious if you have any before/after examples or description of how Righteous behaves, so that one knows what to expect by installing this?

**Comment by pouyakary** [comment]
Hi again @oyeanuj. Hope you're doing great. Thanks a lot for your interest on Righteous. Righteous is designed to handle my custom coding style. [This is just a random example](https://github.com/pmkary/cozy/blob/master/source/core/storage/storage.ts). You can read a bit about [this coding style here](http://kary.us/2017/05/16/my-journey-to-clean-code/)

Before you run it on any serious code please be warned that righteous is designed for my own specific projects and __DEFINITELY EXPERIMENTAL AND NOT READY FOR ANY KIND OF REAL WORLD PROJECTS__.

TypeScript / JavaScript it will look like this:
<img width="760" alt="screen shot 1396-11-29 at 2 33 39 am" src="https://user-images.githubusercontent.com/2157285/36346458-34694f70-1454-11e8-9a9a-b33ad27fb5e5.png">

CSS will look like this:
![](http://kary.us/Graphics/Blog/7936.21.8.26/css-3.png)

But formatters scan the code and then rewrite it with from the AST level so in TypeScript / JavaScript only whitespace and indentations are being formatted. In CSS almost everything get's formatted, the lines are sorted and formatted in table views, extra lines are removed and similar stuff.

**Comment by oyeanuj** [comment]
@pmkary Thank you for the detailed response, it definitely looks clean and readable! Since it isn't ready for real-world use yet, I will try to use it some test project. Looking forward to it being ready for real world use :)

PS. How much flexibility do you foresee providing? Would it be like Eslint/Prettier that there would be some opt-in/opt-out rules for formatting?

**Comment by pouyakary** [comment]
@oyeanuj 

You're welcome! Righteous is not a good thing to be used for any projects. It is stable on TypeScript / JavaScript because it uses TypeScript's internal formatting engine so it is stable. The only place it breaks apart is identifying [my comments](https://github.com/pmkary/comment/wiki).

Also when it comes to CSS the whole thing happens by rewriting the code from the tree. The problem is I develop them as I progress in my other projects so there are so many CSS stuff that I haven't used and so I haven't wrote the formatter for them (just recently I found it cann't format `@font-face`). This problem happens as formatter replaces the unsupported part by writing empty strings (which is a bug by the way) and that's why it's not suitable for any kind of programming. For me it's no problem because just as I find a problem I fix it in the main branch and then I resume my job, but if you want to format your code with Righteous I think you should take that into consideration and apply the same approach.


To your question. In typescript spaces are formatted but the rest of the stuff are still optional by many means. In CSS however almost everything is formatted expect for the property values. Because in CSS there are no grammars for them and I have to develop another parser for them which is really time consuming so I have left them manul

**Comment by oyeanuj** [comment]
Got it, that makes sense! Thanks for the context!
